# Generated by Django 5.2.17 on 2026-09-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('REGULAR_MACHINE', 'ماكينة عادية'), ('PRESS', 'مكبس'), ('SPRING_MACHINE', 'ماكينة سوستة')], db_index=True, max_length=30, verbose_name='النوع')),
                ('asset_code', models.CharField(max_length=100, verbose_name='كود الماكينة')),
                ('sequence_order', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='factories.factory')),
            ],
            options={
                'ordering': ['factory_id', 'asset_type', 'sequence_order', 'id'],
                'indexes': [models.Index(fields=['factory', 'asset_type', 'sequence_order'], name='assets_asse_factory_1cd620_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('factory', 'asset_code'), name='uniq_live_asset_code_factory')],
            },
        ),
    ]
