# Generated by Django 5.2.17 on 2026-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('REGULAR_MACHINE', 'ماكينة حقن'), ('PRESS', 'مكبس'), ('SPRING_MACHINE', 'ماكينة نفخ')], db_index=True, max_length=30, verbose_name='النوع'),
        ),
    ]
