# Generated by Django 5.2.12 on 2026-10-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='custom_type_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم النوع المخصص'),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='اسم الماكينة'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('REGULAR_MACHINE', 'ماكينة حقن'), ('PRESS', 'مكبس'), ('SPRING_MACHINE', 'ماكينة نفخ'), ('EXTRUDER', 'ماكينة سحب / إكسترودر'), ('PRINTING', 'ماكينة طباعة'), ('PACKAGING', 'ماكينة تغليف / تعبئة'), ('CRUSHER', 'كسارة / مطحنة'), ('OTHER', 'نوع آخر / مخصص')], db_index=True, default='REGULAR_MACHINE', max_length=30, verbose_name='النوع'),
        ),
    ]
