# Generated by Django 5.2.12 on 2026-10-10 11:36

import django.db.models.deletion
from django.db import migrations, models


def seed_asset_types(apps, schema_editor):
    AssetType = apps.get_model('assets', 'AssetType')
    Asset = apps.get_model('assets', 'Asset')

    defaults = [
        ("REGULAR_MACHINE", "ماكينة حقن"),
        ("PRESS", "مكبس"),
        ("SPRING_MACHINE", "ماكينة نفخ"),
        ("EXTRUDER", "ماكينة سحب / إكسترودر"),
        ("PRINTING", "ماكينة طباعة"),
        ("PACKAGING", "ماكينة تغليف / تعبئة"),
        ("CRUSHER", "كسارة / مطحنة"),
        ("OTHER", "نوع آخر / مخصص"),
    ]
    created_map = {}
    for code, name in defaults:
        obj, _ = AssetType.objects.get_or_create(code=code, defaults={"name": name})
        created_map[code] = obj

    for asset in Asset.objects.all():
        if asset.asset_type in created_map:
            asset.type_ref = created_map[asset.asset_type]
            asset.save(update_fields=['type_ref'])


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_custom_type_name_asset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم نوع الماكينة')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='كود النوع')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع ماكينة',
                'verbose_name_plural': 'أنواع الماكينات',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('REGULAR_MACHINE', 'ماكينة حقن'), ('PRESS', 'مكبس'), ('SPRING_MACHINE', 'ماكينة نفخ'), ('EXTRUDER', 'ماكينة سحب / إكسترودر'), ('PRINTING', 'ماكينة طباعة'), ('PACKAGING', 'ماكينة تغليف / تعبئة'), ('CRUSHER', 'كسارة / مطحنة'), ('OTHER', 'نوع آخر / مخصص')], db_index=True, default='REGULAR_MACHINE', max_length=50, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assettype', verbose_name='نوع الماكينة'),
        ),
        migrations.RunPython(seed_asset_types, reverse_seed),
    ]
