# Generated by Django 5.2.17 on 2026-09-21 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_asset_type'),
        ('factories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم القائم على الماكينة')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='factories.factory', verbose_name='المصنع')),
            ],
            options={
                'verbose_name': 'القائم على الماكينة',
                'verbose_name_plural': 'القائمون على الماكينات',
                'ordering': ['factory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المنتج')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='كود المنتج')),
                ('weight_per_piece_grams', models.FloatField(blank=True, default=0.0, verbose_name='وزن القطعة (جرام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='factories.factory', verbose_name='المصنع')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['factory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineProductionDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_cavities', models.PositiveIntegerField(default=1, verbose_name='عدد اللقم الأصلي')),
                ('cooling_time_seconds', models.FloatField(default=0.0, verbose_name='زمن التبريد (ثانية)')),
                ('cycle_time_seconds', models.FloatField(default=0.0, verbose_name='زمن الدورة (ثانية)')),
                ('target_cycle_production', models.FloatField(default=0.0, verbose_name='الإنتاج حسب زمن الدورة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_default', to='assets.asset', verbose_name='الماكينة')),
                ('default_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_machines', to='production.product', verbose_name='المنتج الافتراضي')),
            ],
            options={
                'verbose_name': 'إعدادات إنتاج الماكينة',
                'verbose_name_plural': 'إعدادات إنتاج الماكينات',
            },
        ),
        migrations.CreateModel(
            name='ProductionShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_report_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('shift', models.CharField(choices=[('FIRST', 'الوردية الأولى (صباحية)'), ('SECOND', 'الوردية الثانية (مسائية)'), ('THIRD', 'الوردية الثالثة (ليلية)')], default='FIRST', max_length=20, verbose_name='الوردية')),
                ('report_date', models.DateField(db_index=True, verbose_name='تاريخ الوردية')),
                ('started_at_device', models.DateTimeField(blank=True, null=True, verbose_name='بداية الوردية')),
                ('completed_at_device', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الوردية')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING_HANDOVER', 'بانتظار تأكيد استلام الوردية'), ('CONFIRMED', 'تم الاستلام والاعتماد')], db_index=True, default='PENDING_HANDOVER', max_length=30, verbose_name='الحالة')),
                ('handover_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ وتوقيت الاستلام')),
                ('handover_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات الاستلام')),
                ('general_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات عامة عن الوردية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reports', to='factories.factory', verbose_name='المصنع')),
                ('handover_to_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_production_reports', to=settings.AUTH_USER_MODEL, verbose_name='المشرف المستلم')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_production_reports', to=settings.AUTH_USER_MODEL, verbose_name='مشرف الوردية')),
            ],
            options={
                'verbose_name': 'تقرير وردية الإنتاج',
                'verbose_name_plural': 'تقارير ورديات الإنتاج',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم القائم على الماكينة')),
                ('product_name', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم المنتج')),
                ('original_product_name', models.CharField(blank=True, default='', max_length=150, verbose_name='المنتج قبل التغيير')),
                ('product_changed', models.BooleanField(default=False, verbose_name='تم تغيير المنتج')),
                ('original_cavities', models.PositiveIntegerField(default=1, verbose_name='عدد اللقم الأصلي')),
                ('current_cavities', models.PositiveIntegerField(default=1, verbose_name='عدد اللقم الحالية')),
                ('operation_mode', models.CharField(choices=[('AUTO', 'أوتو'), ('MANUAL', 'يدوي')], default='AUTO', max_length=10, verbose_name='حالة التشغيل')),
                ('cooling_time_seconds', models.FloatField(default=0.0, verbose_name='التبريد (ثانية)')),
                ('cycle_time_seconds', models.FloatField(default=0.0, verbose_name='الدورة (ثانية)')),
                ('raw_material', models.CharField(blank=True, default='', max_length=150, verbose_name='الخامة المستخدمة')),
                ('final_production_weight_kg', models.FloatField(default=0.0, verbose_name='وزن الإنتاج النهائي بالكيلو')),
                ('target_cycle_production', models.FloatField(default=0.0, verbose_name='الإنتاج حسب زمن الدورة')),
                ('packaging_type', models.CharField(blank=True, default='', max_length=100, verbose_name='العبوة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات الماكينة')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='assets.asset', verbose_name='الماكينة')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to='production.machineoperator', verbose_name='القائم على الماكينة')),
                ('original_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.product', verbose_name='المنتج الأصلي قبل التغيير')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_entries', to='production.product', verbose_name='المنتج الحالي')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_entries', to='production.productionshiftreport')),
            ],
            options={
                'verbose_name': 'سجل إنتاج ماكينة',
                'verbose_name_plural': 'سجلات إنتاج الماكينات',
                'ordering': ['asset__sequence_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoppage_type', models.CharField(choices=[('MACHINE_BREAKDOWN', 'عطل ماكينة'), ('MOLD_CHANGE', 'تغيير اسطمبة / منتج'), ('FRIDAY_PRAYER', 'إيقاف صلاة الجمعة لجميع الماكينات'), ('POWER_OUTAGE', 'انقطاع كهرباء عام'), ('RAW_MATERIAL_SHORTAGE', 'نقص خامات أو مياه تبريد'), ('OTHER', 'توقف آخر')], default='MACHINE_BREAKDOWN', max_length=30, verbose_name='نوع التوقف / العطل')),
                ('description', models.TextField(verbose_name='وصف العطل أو سبب التوقف')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدة التوقف (بالدقائق)')),
                ('action_taken', models.TextField(blank=True, default='', verbose_name='الإجراء المتخذ / الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stoppages', to='assets.asset', verbose_name='الماكينة (فارغ إذا كان للمصنع كاملاً)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoppages', to='production.productionshiftreport')),
            ],
            options={
                'verbose_name': 'عطل أو توقف',
                'verbose_name_plural': 'الأعطال والتوقفات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionshiftreport',
            constraint=models.UniqueConstraint(fields=('factory', 'report_date', 'shift'), name='uniq_factory_date_shift'),
        ),
    ]
