# Generated by Django 5.2.17 on 2026-09-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineproductiondefault',
            name='default_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_machines', to='production.machineoperator', verbose_name='القائم على الماكينة الافتراضي'),
        ),
        migrations.AddField(
            model_name='machineproductionentry',
            name='operator_changed',
            field=models.BooleanField(default=False, verbose_name='تم تغيير القائم على الماكينة'),
        ),
        migrations.AddField(
            model_name='machineproductionentry',
            name='original_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.machineoperator', verbose_name='القائم على الماكينة الأصلي قبل التغيير'),
        ),
        migrations.AddField(
            model_name='machineproductionentry',
            name='original_operator_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='القائم على الماكينة قبل التغيير'),
        ),
    ]
