# Generated by Django 5.2.12 on 2026-10-04 11:13

import django.db.models.deletion
from django.db import migrations, models


def seed_production_choices(apps, schema_editor):
    Factory = apps.get_model('factories', 'Factory')
    Asset = apps.get_model('assets', 'Asset')
    ProductionOption = apps.get_model('production', 'ProductionOption')
    MachineProductionDefault = apps.get_model('production', 'MachineProductionDefault')
    MachineProductionEntry = apps.get_model('production', 'MachineProductionEntry')
    db = schema_editor.connection.alias
    for factory in Factory.objects.using(db).all():
        kg, _ = ProductionOption.objects.using(db).get_or_create(
            factory_id=factory.pk, category='FINAL_UNIT', name='كجم',
            defaults={'kg_per_unit': 1.0, 'is_active': True},
        )
        for category, names in {
            'FINAL_UNIT': [('بَلفة', None), ('قطعة', None), ('كرتونة', None), ('طن', 1000.0)],
            'CYCLE_UNIT': [('كرتونة', None), ('لقمة', None), ('قطعة', None)],
            'PACKAGING': [('برميل', None), ('كيس', None), ('كرتونة', None), ('برميل + كيس', None)],
        }.items():
            for name, kg_per_unit in names:
                ProductionOption.objects.using(db).get_or_create(
                    factory_id=factory.pk, category=category, name=name,
                    defaults={'kg_per_unit': kg_per_unit, 'is_active': True},
                )
        legacy_materials = MachineProductionEntry.objects.using(db).filter(
            report__factory_id=factory.pk,
        ).exclude(raw_material='').values_list('raw_material', flat=True).distinct()
        for name in legacy_materials:
            name = name.strip()
            if not name:
                continue
            ProductionOption.objects.using(db).get_or_create(
                factory_id=factory.pk, category='RAW_MATERIAL', name=name.strip(),
                defaults={'is_active': True},
            )
        MachineProductionDefault.objects.using(db).filter(asset__factory_id=factory.pk).update(default_final_unit_id=kg.pk)
        for asset in Asset.objects.using(db).filter(factory_id=factory.pk).iterator():
            MachineProductionDefault.objects.using(db).get_or_create(
                asset_id=asset.pk,
                defaults={'default_final_unit_id': kg.pk, 'original_cavities': 1},
            )
        MachineProductionEntry.objects.using(db).filter(report__factory_id=factory.pk).update(
            final_production_quantity=models.F('final_production_weight_kg'),
            final_production_unit_name='كجم',
            final_production_unit_id=kg.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
        ('production', '0002_machineproductiondefault_default_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineproductionentry',
            name='final_production_quantity',
            field=models.FloatField(default=0.0, verbose_name='كمية الإنتاج النهائي'),
        ),
        migrations.AddField(
            model_name='machineproductionentry',
            name='final_production_unit_name',
            field=models.CharField(blank=True, default='كجم', max_length=100, verbose_name='وحدة كمية الإنتاج'),
        ),
        migrations.AddField(
            model_name='machineproductionentry',
            name='target_cycle_unit_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='وحدة مستهدف الدورة'),
        ),
        migrations.CreateModel(
            name='ProductionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RAW_MATERIAL', 'خامة'), ('FINAL_UNIT', 'وحدة الإنتاج الفعلي'), ('CYCLE_UNIT', 'وحدة مستهدف الدورة'), ('PACKAGING', 'عبوة')], db_index=True, max_length=20, verbose_name='نوع الاختيار')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('kg_per_unit', models.FloatField(blank=True, null=True, verbose_name='الوزن بالكيلو لكل وحدة (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_options', to='factories.factory', verbose_name='المصنع')),
            ],
            options={
                'verbose_name': 'اختيار إنتاج',
                'verbose_name_plural': 'اختيارات الإنتاج',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='machineproductiondefault',
            name='default_final_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_final_unit_machines', to='production.productionoption', verbose_name='وحدة الإنتاج الفعلي الافتراضية'),
        ),
        migrations.AddField(
            model_name='machineproductiondefault',
            name='default_packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_packaging_machines', to='production.productionoption', verbose_name='العبوة الافتراضية'),
        ),
        migrations.AddField(
            model_name='machineproductiondefault',
            name='default_raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_material_machines', to='production.productionoption', verbose_name='الخامة الافتراضية'),
        ),
        migrations.AddField(
            model_name='machineproductiondefault',
            name='target_cycle_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_cycle_machines', to='production.productionoption', verbose_name='وحدة مستهدف الدورة'),
        ),
        migrations.AddField(
            model_name='machineproductionentry',
            name='final_production_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to='production.productionoption', verbose_name='وحدة الإنتاج الفعلي'),
        ),
        migrations.AddConstraint(
            model_name='productionoption',
            constraint=models.UniqueConstraint(fields=('factory', 'category', 'name'), name='uniq_production_option_factory_category_name'),
        ),
        migrations.RunPython(seed_production_choices, migrations.RunPython.noop),
    ]
