# Generated by Django 5.2.17 on 2026-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم المستخدم'),
        ),
    ]
