# Generated by Django 5.2.17 on 2026-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مسؤول النظام'), ('MAINTENANCE_SUPERVISOR', 'مشرف صيانة'), ('PRODUCTION_SUPERVISOR', 'مشرف إنتاج')], default='MAINTENANCE_SUPERVISOR', max_length=32, verbose_name='الدور'),
        ),
    ]
