# Generated by Django 5.2.17 on 2026-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مسؤول النظام'), ('MAINTENANCE_SUPERVISOR', 'مشرف صيانة'), ('PRODUCTION_SUPERVISOR', 'مشرف إنتاج وأعطال'), ('GENERAL_SUPERVISOR', 'مشرف صيانة وإنتاج')], default='MAINTENANCE_SUPERVISOR', max_length=32, verbose_name='الدور والصلاحيات'),
        ),
    ]
