# Generated by Django 5.2.17 on 2026-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, choices=[('FIRST', 'الوردية الأولى (صباحية)'), ('SECOND', 'الوردية الثانية (مسائية)'), ('THIRD', 'الوردية الثالثة (ليلية)')], help_text='حدد الوردية المخصصة للمشرف في المصنع ليظهر له تقرير الوردية السابقة للتأكيد تلقائياً.', max_length=20, null=True, verbose_name='الوردية المسندة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '👑 مسؤول عام (كافة الصلاحيات والمصانع)'), ('MAINTENANCE_SUPERVISOR', '🛠️ مشرف صيانة دورية (صلاحيات الصيانة لمصنعه فقط)'), ('PRODUCTION_SUPERVISOR', '🏭 مشرف إنتاج وأعطال (صلاحيات الإنتاج والأعطال لمصنعه فقط)'), ('GENERAL_SUPERVISOR', '⚡ مشرف عام للمصنع (صيانة وإنتاج لمصنعه فقط)')], default='MAINTENANCE_SUPERVISOR', max_length=32, verbose_name='الدور والصلاحيات'),
        ),
    ]
