# Generated by Django 5.2.17 on 2026-09-17 08:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('factories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sequence_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sequence_order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='maintenance.checklistsection')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='maintenance.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='FactoryMaintenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('order_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_states', to='assets.asset')),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_state', to='factories.factory')),
                ('last_completed_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_for_states', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_report_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('report_date', models.DateField(db_index=True)),
                ('started_at_device', models.DateTimeField()),
                ('completed_at_device', models.DateTimeField()),
                ('last_modified_at_device', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='assets.asset')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='factories.factory')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_answers', to='maintenance.checklistitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='maintenance.maintenancereport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('section', 'sequence_order'), name='uniq_item_order'),
        ),
        migrations.AddConstraint(
            model_name='checklistsection',
            constraint=models.UniqueConstraint(fields=('template', 'sequence_order'), name='uniq_section_order'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['factory', 'report_date'], name='maintenance_factory_7b102f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['asset', 'report_date'], name='maintenance_asset_i_e4064e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['supervisor', 'report_date'], name='maintenance_supervi_efb35e_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancereport',
            constraint=models.UniqueConstraint(fields=('factory', 'report_date'), name='uniq_factory_report_date'),
        ),
        migrations.AddConstraint(
            model_name='maintenancereport',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at_device__gte', models.F('started_at_device'))), name='report_device_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='maintenancereportitem',
            constraint=models.UniqueConstraint(fields=('report', 'checklist_item'), name='uniq_report_item'),
        ),
    ]
