# Generated by Django 5.2.17 on 2026-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_seed_allowed_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorymaintenancestate',
            name='current_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
