# Generated by Django 5.2.17 on 2026-09-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('maintenance', '0004_factorymaintenancestate_manual_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyMaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(verbose_name='العطل')),
                ('responsible_person', models.CharField(max_length=150, verbose_name='المسؤول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_maintenances', to='assets.asset')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_items', to='maintenance.maintenancereport')),
            ],
            options={
                'verbose_name': 'بند صيانة طارئة',
                'verbose_name_plural': 'بنود الصيانة الطارئة',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
