# Generated by Django 5.2.17 on 2026-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_emergencymaintenanceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='cleaner_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='القائم بالنظافة'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='electrical_technician',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='القائم بالصيانة الكهربية'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='maintenance_manager',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='مدير الصيانة'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='mechanical_technician',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='القائم بالصيانة الميكانيكية'),
        ),
    ]
