# Generated by Django 5.2.17 on 2026-09-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('maintenance', '0006_maintenancereport_cleaner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorymaintenancestate',
            name='current_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_states', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='factorymaintenancestate',
            name='last_completed_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_for_states', to='assets.asset'),
        ),
    ]
